Update snyk_test_delta_2.yml

diff --git a/.github/workflows/snyk_test_delta_2.yml b/.github/workflows/snyk_test_delta_2.yml
--- a/.github/workflows/snyk_test_delta_2.yml
+++ b/.github/workflows/snyk_test_delta_2.yml
@@ -73,36 +73,38 @@ jobs:
         CHANGED_FILES=$(echo "${{ steps.get_changed_files.outputs.changed_files }}")
         TARGET_REPO="${{ github.repository }}"
         SNYK_ORG_ID="${{ secrets.SNYK_ORG_ID }}"
-        BASELINE_PROJECT_ID="f9b13c77-b5d6-4ab4-83e7-9b93bd9bf283" # Replace with the actual Snyk Project ID of your baseline
+        BASELINE_PROJECT_ID="f0a5bb13-e1f6-4d51-8e08-90c39a2b8a82" # Replace with the actual Snyk Project ID of your baseline
+        SNYK_BASELINE_ORG_ID="964eae1d-53ee-4e80-a0c5-8b0bb6b262d3"
+        TARGET_PROJECT_ID="f9b13c77-b5d6-4ab4-83e7-9b93bd9bf283"
 
         echo "Snyk Organization ID: $SNYK_ORG_ID"
         echo "Baseline Snyk Project ID (Configured): $BASELINE_PROJECT_ID"
 
         # Fetch all projects in the Snyk organization
-        echo "Fetching all Snyk projects for org: $SNYK_ORG_ID"
-        ALL_PROJECTS_JSON=$(curl -s -H "Authorization: token ${{ secrets.SNYK_API_TOKEN }}" "https://api.snyk.io/rest/orgs/$SNYK_ORG_ID/projects?limit=1000") # Adjust limit if needed
+        #echo "Fetching all Snyk projects for org: $SNYK_ORG_ID"
+        #ALL_PROJECTS_JSON=$(curl -s -H "Authorization: token ${{ secrets.SNYK_API_TOKEN }}" "https://api.snyk.io/rest/orgs/$SNYK_ORG_ID/projects?limit=1000") # Adjust limit if needed
 
         if [ -n "$ALL_PROJECTS_JSON" ]; then
           echo "Processing changed files..."
           while IFS= read -r file; do
             echo "Processing file: $file"
             FILE_PATH="$file"
-            TARGET_PROJECT_ID="" # Initialize
+           # #TARGET_PROJECT_ID="" # Initialize
 
             # Find the Snyk project ID for the current repository
-            POTENTIAL_PROJECT_ID=$(echo "$ALL_PROJECTS_JSON" | jq -r ".data[] | select(.attributes.target.name == \"$TARGET_REPO\") | .id" || true)
+            #POTENTIAL_PROJECT_ID=$(echo "$ALL_PROJECTS_JSON" | jq -r ".data[] | select(.attributes.target.name == \"$TARGET_REPO\") | .id" || true)
 
-            if [ -n "$POTENTIAL_PROJECT_ID" ]; then
-              TARGET_PROJECT_ID="$POTENTIAL_PROJECT_ID"
-              echo "Found Target Snyk Project ID for repository '$TARGET_REPO': $TARGET_PROJECT_ID"
-            else
-              echo "Warning: Could not find a Snyk project for repository: $TARGET_REPO. Skipping delta for file: $FILE_PATH"
-              continue
-            fi
+            #if [ -n "$POTENTIAL_PROJECT_ID" ]; then
+             # TARGET_PROJECT_ID="$POTENTIAL_PROJECT_ID"
+             # echo "Found Target Snyk Project ID for repository '$TARGET_REPO': $TARGET_PROJECT_ID"
+            #else
+             # echo "Warning: Could not find a Snyk project for repository: $TARGET_REPO. Skipping delta for file: $FILE_PATH"
+              #continue
+            #fi
 
             if [ -n "$TARGET_PROJECT_ID" ] && [ -n "$BASELINE_PROJECT_ID" ]; then
               echo "Running snyk delta between project ID '$BASELINE_PROJECT_ID' and '$TARGET_PROJECT_ID'"
-              snyk-delta --baselineOrg="$SNYK_ORG_ID" --baselineProject="$BASELINE_PROJECT_ID" --currentOrg="$SNYK_ORG_ID" --currentProject="$TARGET_PROJECT_ID"
+              snyk-delta --baselineOrg="$SNYK_BASELINE_ORG_ID" --baselineProject="$BASELINE_PROJECT_ID" --currentOrg="$SNYK_ORG_ID" --currentProject="$TARGET_PROJECT_ID"
               echo "-------------------------"
             else
               echo "Warning: Could not determine target or baseline Snyk Project ID for file: $FILE_PATH"
