Update snyk_test_delta.yml

diff --git a/.github/workflows/snyk_test_delta.yml b/.github/workflows/snyk_test_delta.yml
--- a/.github/workflows/snyk_test_delta.yml
+++ b/.github/workflows/snyk_test_delta.yml
@@ -66,31 +66,47 @@ jobs:
       run: |
         # Get the previous commit hash
         PREVIOUS_COMMIT=$(git rev-parse HEAD^1)
+        if [ $? -ne 0 ]; then
+          echo "Error: Unable to retrieve the previous commit hash."
+          exit 1
+        fi
         echo "Previous Commit: $PREVIOUS_COMMIT"
-        echo "Exit Code: $?"
     
         # Get the list of modified files since the previous commit
         git diff --name-only "$PREVIOUS_COMMIT" HEAD > changed_files.txt
-        echo "Exit Code: $?"
+        if [ $? -ne 0 ]; then
+          echo "Error: Failed to retrieve the list of changed files."
+          exit 1
+        fi
     
-        # Filter for relevant files ...
+        # Filter for relevant files
         grep -E '\.(csproj|sln|lock|json)$' changed_files.txt > relevant_changed_files.txt
-        echo "Exit Code: $?"
+        if [ $? -ne 0 ]; then
+          echo "Error: Failed to filter relevant files."
+          exit 1
+        fi
     
         if [ -s "relevant_changed_files.txt" ]; then
-          echo "Running Snyk Delta on the following changed files since commit $PREVIOUS_COMMIT:"
+          echo "Running Snyk Delta on the following relevant files:"
           cat relevant_changed_files.txt
+          
+          errors=0
           while IFS= read -r file; do
             echo "Scanning delta for: $file"
-            output=$(snyk delta --file="$file" --org=*** --base="$PREVIOUS_COMMIT" HEAD)
-            echo "Snyk Delta Output for $file:"
-            echo "$output"
+            snyk delta --file="$file" --org=*** --base="$PREVIOUS_COMMIT" HEAD
             exit_code=$?
-            echo "Snyk Delta Exit Code: $exit_code"
             if [ $exit_code -ne 0 ]; then
-              echo "Snyk Delta found issues or encountered an error for $file."
+              echo "Error: Snyk Delta encountered an issue for $file."
+              errors=$((errors + 1))
             fi
           done < "relevant_changed_files.txt"
+    
+          if [ $errors -ne 0 ]; then
+            echo "Snyk Delta encountered issues with $errors file(s)."
+            exit 1
+          else
+            echo "Snyk Delta analysis completed successfully."
+          fi
         else
           echo "No relevant files changed in this push for Snyk Delta analysis."
         fi
